name: pocknet
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - biopython
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - fastparquet
  - gcc
  - gxx
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - ld_impl_linux-64
  - libffi
  - libgcc
  - libgcc-ng
  - liblzma
  - liblzma-devel
  - libsodium
  - libstdcxx
  - libstdcxx-ng
  - libuuid
  - libzlib
  - llvm-openmp
  - matplotlib
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - notebook
  - numpy
  - openbabel
  - openssl
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pyarrow
  - pygments
  - pymol-open-source
  - python=3.10
  - python-dateutil
  - python_abi
  - pyzmq
  - readline
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - xz
  - xz-gpl-tools
  - xz-tools
  - zeromq
  - zipp
  - zlib
  - pip:
    - biopython==1.85
    - hopular==1.0.0
    - hydra-colorlog==1.2.0
    - hydra-core==1.3.2
    - imbalanced-learn==0.13.0
    - lightning==2.5.0.post0
    - nglview==3.1.4
    - py3Dmol==2.4.2
    - pytorch-tabnet==4.1.0
    - rich==13.9.4
    - rootutils==1.0.7
    - torch==2.5.1+cu121
    - torchaudio==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - wandb==0.19.4
    - xgboost==3.0.0