version: 1
formatters:
  colorlog:
    (): colorlog.ColoredFormatter
    format: "[%(cyan)s%(asctime)s%(reset)s][%(blue)sHYDRA%(reset)s] %(message)s"
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red,bg_white

handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console]

disable_existing_loggers: false