# @package model

defaults:
  - default

_target_: src.models.tabnet_binding_site_module.TabNetBindingSiteModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

n_d: 128
n_a: 128
n_steps: 8
gamma: 1.5
cat_idxs: []
cat_dims: []
use_iou_metric: true