_target_: src.models.hopular_binding_site_module.HopularBindingSiteModule
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
# Model hyperparameters
hidden_dim: 128
hopfield_dim: 64
heads: 4
scaling: null
dropout: 0.1
layers: 3
pattern_dim: 32
update_steps: 1
polynomial_degree: 2
use_iou_metric: true