_target_: src.models.xgboost_binding_site_module.XGBoostBindingSiteModule
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
# XGBoost hyperparameters
learning_rate: 0.1
max_depth: 6
n_estimators: 300  # Increased number of trees for better performance
subsample: 0.8
colsample_bytree: 0.8
gamma: 0.1
reg_alpha: 0.1
reg_lambda: 1.0
use_iou_metric: true